### ISSUE TITLE
The New SnapMod doesn't load and stuck at snapchat logo splash screen

### ISSUE THREAD

**Issue by RevealedSoulEven** [rodit/SnapMod#252]
As mentioned in the title. Here are the logs

`[ 2022-09-23T22:25:05.955        0:   714:  1207 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/verbose_2022-09-23T22:25:05.954.log
[ 2022-09-23T22:25:12.184    10345:  4755:  4755 I/LSPosed         ] Loading xposed for com.snapchat.android/10345
[ 2022-09-23T22:25:12.191    10345:  4755:  4755 I/LSPosed-Bridge  ] Loading module xyz.rodit.snapmod from /data/app/~~ECy5fh6j1VYPWuWwG_hRmQ==/xyz.rodit.snapmod-hFjsMXOdV3jzWSVcdyEQBg==/base.apk
[ 2022-09-23T22:25:12.311    10345:  4755:  4755 I/LSPosed-Bridge  ]   Loading class xyz.rodit.snapmod.SnapHooks
[ 2022-09-23T22:25:12.392    10345:  4755:  4755 I/LSPosed-Bridge  ] Context hook com.snap.mushroom.app.MushroomApplication@85411c7, [android.app.ContextImpl@dc17de1]
[ 2022-09-23T22:25:12.594    10345:  4755:  4755 I/LSPosed-Bridge  ] Loaded cached mappings for build 84641.
[ 2022-09-23T22:25:12.622    10345:  4755:  6838 I/LSPosed-Bridge  ] SnapHooks/error: Uncaught exception on thread Thread[ui_bg-0,5,main].
[ 2022-09-23T22:25:12.622    10345:  4755:  6838 I/LSPosed-Bridge  ] SnapHooks/error: zKh: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.UnsatisfiedLinkError: dlopen failed: library "libclient.so" not found
[ 2022-09-23T22:25:12.737    10345:  4755:  4755 I/LSPosed-Bridge  ] Crash unexpectedly: android.view.InflateException: Binary XML file line #34 in com.snapchat.android:layout/ngs_main_camera_navigation: Binary XML file line #34 in com.snapchat.android:layout/ngs_main_camera_navigation: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #34 in com.snapchat.android:layout/ngs_main_camera_navigation: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:856)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1125)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:684)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.inflate(Unknown Source:25)
	at Qvf.inflate(SourceFile:2)
	at aB1.v3(SourceFile:3)
	at aB1.Z1(Unknown Source:15)
	at wI6.y2(Unknown Source:20)
	at OI6.i0(SourceFile:20)
	at OI6.g0(Unknown Source:38)
	at OI6.h0(Unknown Source:46)
	at nu0.j(SourceFile:8)
	at OI6.U(SourceFile:7)
	at OI6.o0(Unknown Source:88)
	at nu0.g(SourceFile:3)
	at YUb.c(Unknown Source:0)
	at YUb.b(SourceFile:14)
	at YUb.g(SourceFile:3)
	at vVb.f(SourceFile:13)
	at Qcb.L(SourceFile:28)
	at gI9.q(SourceFile:2)
	at gI9.k(SourceFile:4)
	at com.snap.mushroom.MainActivity.onPostCreate(Unknown Source:21)
	at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1386)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3652)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2172)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8163)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:972)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f08092c
	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:248)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:999)
	at android.content.res.Resources.getDrawable(Resources.java:939)
	at android.content.res.Resources.getDrawable(Resources.java:914)
	at iw5.<init>(SourceFile:1)
	at ZW4.<init>(Unknown Source:85)
	at jI6.D(SourceFile:3)
	at com.snap.camera.ui.takesnapbutton.TakeSnapButton.<init>(SourceFile:3)
	... 45 more
[ 2022-09-23T22:25:12.738    10345:  4755:  4755 E/AndroidRuntime  ] FATAL EXCEPTION: main
Process: com.snapchat.android, PID: 4755
android.view.InflateException: Binary XML file line #34 in com.snapchat.android:layout/ngs_main_camera_navigation: Binary XML file line #34 in com.snapchat.android:layout/ngs_main_camera_navigation: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #34 in com.snapchat.android:layout/ngs_main_camera_navigation: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:856)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1125)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:684)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.inflate(Unknown Source:25)
	at Qvf.inflate(SourceFile:2)
	at aB1.v3(SourceFile:3)
	at aB1.Z1(Unknown Source:15)
	at wI6.y2(Unknown Source:20)
	at OI6.i0(SourceFile:20)
	at OI6.g0(Unknown Source:38)
	at OI6.h0(Unknown Source:46)
	at nu0.j(SourceFile:8)
	at OI6.U(SourceFile:7)
	at OI6.o0(Unknown Source:88)
	at nu0.g(SourceFile:3)
	at YUb.c(Unknown Source:0)
	at YUb.b(SourceFile:14)
	at YUb.g(SourceFile:3)
	at vVb.f(SourceFile:13)
	at Qcb.L(SourceFile:28)
	at gI9.q(SourceFile:2)
	at gI9.k(SourceFile:4)
	at com.snap.mushroom.MainActivity.onPostCreate(Unknown Source:21)
	at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1386)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3652)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2172)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8163)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:972)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f08092c
	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:248)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:999)
	at android.content.res.Resources.getDrawable(Resources.java:939)
	at android.content.res.Resources.getDrawable(Resources.java:914)
	at iw5.<init>(SourceFile:1)
	at ZW4.<init>(Unknown Source:85)
	at jI6.D(SourceFile:3)
	at com.snap.camera.ui.takesnapbutton.TakeSnapButton.<init>(SourceFile:3)
	... 45 more
[ 2022-09-23T22:25:12.760    10345:  4755:  6848 I/LSPosed-Bridge  ] SnapHooks/error: Uncaught exception on thread Thread[inflation-0,5,main].
[ 2022-09-23T22:25:12.760    10345:  4755:  6848 I/LSPosed-Bridge  ] SnapHooks/error: dc0: FBb: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | android.content.res.Resources$NotFoundException: Resource ID #0x7f080996 on scheduler CrashReporting.CrashManagerImpl tid=12960 
[ 2022-09-23T22:25:20.315     1000:  1841:  2244 I/LSPosed-Bridge  ] FL: [Shaomi R] in handleGpsLocationChangedLocked! Caller packageName: android
[ 2022-09-23T22:25:20.334     1000:  1841:  2244 E/LSPosed-Bridge  ] kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Unresolved class: class java.lang.String
	at kotlin.reflect.jvm.internal.KClassImpl.reportUnresolvedClass(KClassImpl.kt:328)
	at kotlin.reflect.jvm.internal.KClassImpl.access$reportUnresolvedClass(KClassImpl.kt:44)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:56)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:48)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt:48)
	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:182)
	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:44)
	at kotlin.reflect.full.KClassifiers.createType(KClassifiers.kt:48)
	at kotlin.reflect.jvm.internal.ReflectionFactoryImpl.typeOf(ReflectionFactoryImpl.java:124)
	at kotlin.jvm.internal.Reflection.typeOf(Reflection.java:127)
	at fuck.location.xposed.helpers.ConfigGateway.inWhitelistOrNot(ConfigGateway.kt:380)
	at fuck.location.xposed.helpers.ConfigGateway.access$inWhitelistOrNot(ConfigGateway.kt:31)
	at fuck.location.xposed.helpers.ConfigGateway$hookWillChangeBeEnabled$2$1.invoke(ConfigGateway.kt:79)
	at fuck.location.xposed.helpers.ConfigGateway$hookWillChangeBeEnabled$2$1.invoke(ConfigGateway.kt:75)
	at com.github.kyuubiran.ezxhelper.utils.XposedHookUtilFactory.beforeHookedMethod(HookUtils.kt:357)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.setProcessMemoryTrimLevel(Unknown Source:25)
	at android.app.ActivityManager.setProcessMemoryTrimLevel(ActivityManager.java:3665)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.hiddenapibypass.HiddenApiBypass.invoke(Unknown Source:102)
	at fuck.location.xposed.helpers.ConfigGateway.universalAPICaller(ConfigGateway.kt:249)
	at fuck.location.xposed.helpers.ConfigGateway.inWhitelist(ConfigGateway.kt:260)
	at fuck.location.xposed.location.miui.MiuiBlurLocationManagerHookerR$hookGetBlurryLocation$10.invoke(MiuiBlurLocationManagerHookerR.kt:193)
	at fuck.location.xposed.location.miui.MiuiBlurLocationManagerHookerR$hookGetBlurryLocation$10.invoke(MiuiBlurLocationManagerHookerR.kt:189)
	at com.github.kyuubiran.ezxhelper.utils.HookUtilsKt$hookBefore$1.beforeHookedMethod(HookUtils.kt:39)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.handleGpsLocationChangedLocked(Unknown Source:14)
	at com.android.server.location.LocationManagerService.requestLocationUpdatesLocked(LocationManagerService.java:2159)
	at com.android.server.location.LocationManagerService.requestLocationUpdates(LocationManagerService.java:2108)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1192)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1152)
	at com.android.server.location.gnss.GnssLocationProvider.handleRequestLocation(GnssLocationProvider.java:901)
	at com.android.server.location.gnss.GnssLocationProvider.access$2700(GnssLocationProvider.java:106)
	at com.android.server.location.gnss.GnssLocationProvider$ProviderHandler.handleMessage(GnssLocationProvider.java:2377)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:237)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:45)
`

**Comment by Lucky-069** [comment]
This does not happens with me. Working fine!

**Comment by authorisation** [comment]
Have you tried reinstalling Snapchat? Also next time please upload the logs in a text file.

**Comment by RSR1337** [comment]
@authorisation 
-There is also an bug where you cannot see your snaps when you click on it (in the public profile)
 -Also, the save feature is not working

**Comment by RevealedSoulEven** [comment]
Umm.... I did it. But still

**Comment by RevealedSoulEven** [comment]
Sorry! My bad!
I downloaded the correct version snapchat apk but the apk size was 39mb (from apkpure I guess) and I had doubt how it can be too less. Now I downlaoded the apk from another website and it's 139 mb something and now it's working
